# Generated by Django 2.2.6 on 2019-12-03 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('estacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('localizacion', models.CharField(max_length=50)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('calle_primaria', models.CharField(max_length=150)),
                ('calle_secundaria', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=13)),
                ('celular', models.CharField(max_length=13)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('persona_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.TextField(default='sin dirección', max_length=50)),
                ('telefono', models.CharField(max_length=13)),
                ('celular', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('sitio_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('Estacionamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Estacionamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('vehiculo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('costoHora', models.DecimalField(decimal_places=3, max_digits=10)),
                ('costoTotal', models.DecimalField(decimal_places=3, max_digits=10)),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Persona')),
                ('Sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('cuenta_id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50, unique=True)),
                ('clave', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Persona')),
            ],
        ),
    ]
