# Generated by Django 2.2.6 on 2019-12-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
